### PR TITLE
Add dimmer pinout + schematic

### PR DESCRIPTION
**Pull request by rosek86**

### CODE REVIEW

**Comment by basilfx** [comment]
Thank you!

**Comment by oliv3r** [comment]
@rosek86 do you happen to have any photo's of the dimmer and its PCB? the only thing that even comes remotely close to the dimmer photo's is https://images.idgesg.net/images/article/2017/09/ikea3-100736352-orig.jpg. I was looking for FCC data but did not find anything yet.

**Comment by rosek86** [comment]
@oliv3r Are you looking for dimmer or motion sensor, please? It seems that the linked photo shows motion sensor. I have a few dimmer photos with an initial layout which shows components placement:[https://www.dropbox.com/sh/1gwytsvfwcgbgle/AACv-0cxXX0uJ0-7y6cXhHLta?dl=0](url)

I don't have any photos of the motion sensor.

**Comment by oliv3r** [comment]
ah right of course, I got confused :) but even so, do you mind if I add your dropbox pictures of the inside of the dimmer? (We already can get them from the FCC document, but your photo's are probably a a little better.
Sadly you don seem to have a populated picture anymore?

**Comment by rosek86** [comment]
Hi @oliv3r,

I will be able to take more photos of the dimmer on Tuesday. I'll get these together and create a pull request.

**Pull request merged**
