### PR TITLE
Document ICPSLC24-10NA

### PR DESCRIPTION
**Pull request by oliv3r**
This series adds the teardown and schematics of the ICSPLC24-10NA PWM output controller module found in LED drivers such as the ICPSHC24-30EU-IL-1 and ICSHC24-10EU-IL-1.

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>

### CODE REVIEW

**Comment by oliv3r** [comment]
anything else you want to see changed here @basilfx ?

**Comment by oliv3r** [comment]
@basilfx Anything you want done or added for this merge?

**Comment by basilfx** [comment]
Hey @oliv3r, thanks for this PR. I have been really busy with other things (and holidays) that I just don't have the time. Sorry!

I only have a comment on where the schema resides: I'd like to keep the `pcb/` folder for things we can build. One suggestion is to move this to the `teardowns/` folder? What do you think? Maybe we have to split the teardown folder per project into `pictures` and `schemas` then.

**Comment by oliv3r** [comment]
To be fair, we CAN build it using the schematics :) but I do agree, it is far better suited to be put under teardowns.

I'll think of some scheme to split the pictures and schemas as well though your suggestion makes quite sense. I'll rework the others once I've glanced at it.

**Comment by oliv3r** [comment]
After a quick peek at the others, there's no need to clean anything in the current state yet. So I only reworked this one and moved the files around as per request. So @basilfx you can merge this one if there's nothing else, and I'll rebase and cleanup the other PR's.

**Comment by basilfx** [comment]
Looks good, thanks!

**Pull request merged**
