### PR TITLE
Add IKEA PARASOLL door/window sensor

### PR DESCRIPTION
**Pull request by basilfx**
I've been investigating this sensor, so I might be able to build a smaller version with a CR2032 battery (or bigger).

Reason to do so, is that I can build this inside of a door frame.

### CODE REVIEW

**Comment by MattWestb** [comment]
Great tear down !!!
And IKEA is using one MG24 chip !!

Can you explaining how to open the sensor in one easy way and if its possible doing it without braking it complexly ?

**Comment by basilfx** [comment]
I had a hard time to open one, but I had no intentions of putting it back together. I bought another one and this time I try the heat gun to loosen the glue.

**Comment by MattWestb** [comment]
I was putting 2 GU10 on the stowen at low temperature for some minutes and its was very easy getting the lince out of them then the glue was soft so being recommended but not too warm for the plastic devices.

**Comment by basilfx** [comment]
Tried to open another one, but I conclude that this is not viable (and safe for your fingers).

Tried to heat it up to 90 degrees Celsius in the stove, but that did not work. Then tried to cut into the glue from the sides, did not work either. Finally took the heat gun at 200 degrees Celsius, but still no luck. While the case becomes soft, the glue still holds it together.

**Comment by MattWestb** [comment]
So they have using better glue and very tight tolerance.
Thanks for info !!

PS: Was getting one old outlet playing then it was being putted on and was putting it in  the owen and then the glue was soft for very short time and was nearly no damage then piling it up (most i have seen have using dremmel or one hammer and . . )
and changing first capacitor from the mains side and it is up and running for some more mounts now.

**Pull request merged**
